### ISSUE TITLE
React-native

### ISSUE THREAD

**Issue by bennyhodl** [nostr-dev-kit/ndk-react#3]
I would like to use ndk for react-native but there are issues with BigInt's and haven't found a shim solution for it.

Any insight in working with react-native?

**Comment by jinglescode** [comment]
try https://www.npmjs.com/package/bigint-polyfill

**Comment by bennyhodl** [comment]
> try https://www.npmjs.com/package/bigint-polyfill

Seems to be not compatible with hermes
```
TypeError: Cannot call a class as a function, js engine: hermes 
```

**Comment by jinglescode** [comment]
i remember there are configs to adjust, to use or not to use hermes, or how to config with hermes. 
do search around in the react native space for answers.
